INSERT INTO ORDERS
(ORDER_DETAIL, QUANTITY, QUANTITY_UNIT, USER_ID, ORDER_DATE)
values
('TV', 1, 'pcs', 'amarsingh', CURDATE());


INSERT INTO ORDERS
(ORDER_DETAIL, QUANTITY, QUANTITY_UNIT, USER_ID, ORDER_DATE)
values
('FRIDGE', 1, 'pcs', 'amarsingh', CURDATE());

INSERT INTO ORDERS
(ORDER_DETAIL, QUANTITY, QUANTITY_UNIT, USER_ID, ORDER_DATE)
values
('AC', 1, 'pcs', 'amarsingh', CURDATE());

INSERT INTO ORDERS
(ORDER_DETAIL, QUANTITY, QUANTITY_UNIT, USER_ID, ORDER_DATE)
values
('BEAN BAG', 1, 'pcs', 'amarsingh', CURDATE());

INSERT INTO ORDERS
(ORDER_DETAIL, QUANTITY, QUANTITY_UNIT, USER_ID, ORDER_DATE)
values
('BEAN', 1, 'KG', 'amarsingh', CURDATE());

INSERT INTO ORDERS
(ORDER_DETAIL, QUANTITY, QUANTITY_UNIT, USER_ID, ORDER_DATE)
values
('WATCH', 1, 'pcs', 'amarsingh', CURDATE());

INSERT INTO ORDERS
(ORDER_DETAIL, QUANTITY, QUANTITY_UNIT, USER_ID, ORDER_DATE)
values
('TABLE', 1, 'pcs', 'amarsingh', CURDATE());

INSERT INTO ORDERS
(ORDER_DETAIL, QUANTITY, QUANTITY_UNIT, USER_ID, ORDER_DATE)
values
('CHAIR', 1, 'pcs', 'amarsingh', CURDATE());

INSERT INTO ORDERS
(ORDER_DETAIL, QUANTITY, QUANTITY_UNIT, USER_ID, ORDER_DATE)
values
('SOFA', 1, 'pcs', 'amarsingh', CURDATE());